### ISSUE TITLE
Typo in website on Policy?

### ISSUE THREAD

**Issue by EdwardIII** [jSherz/codebuild-codepipeline-badges#1]
Hey, thanks for putting all this together.

Just working on creating a cloudformation template for this.

On https://jsherz.com/codebuild/aws/lambda/cloudwatch/nodejs/readme/2017/11/06/codebuild-badges.html you have this example:

    {
        "Version": "2012-10-17",
        "Statement": [
            {
                "Effect": "AllowLoggingToCloudWatch",
                "Action": [
                    "logs:CreateLogGroup",
                    "logs:CreateLogStream",
                    "logs:PutLogEvents"
                ],
                "Resource": "arn:aws:logs:*:*:*"
            },
            {
                "Sid": "AllowUploadingBadges",
                "Effect": "Allow",
                "Action": [
                    "s3:PutObject",
                    "s3:PutObjectAcl"
                ],
                "Resource": [
                    "arn:aws:s3:::BUCKET_NAME/*"
                ]
            }
        ]
    }

Not 100% sure but I think this:

    "Effect": "AllowLoggingToCloudWatch",

Should be this?

    "Sid": "AllowLoggingToCloudWatch",
    "Effect": "Allow",

**Comment by jSherz** [comment]
Great catch! Thank you very much for spotting that and letting me know - I'll fix it today.

**Comment by EdwardIII** [comment]
Cool! I'll send a link to my cloudformation template when I can get the stupid thing working.

**Comment by jSherz** [comment]
Policy fixed! Thanks again for letting me know :+1:
